name: Trigger Render Deploy

on:
  workflow_dispatch:

  schedule:
    - cron: '*/10 * * * *'  # every 30 minutes

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger redeploy on Render
        run: curl -X POST https://api.render.com/deploy/srv-d05o1k3uibrs73ft4m30?key=zQAFpQFpp94
